#!/usr/bin/env python3

import os
import sys
import shutil
import time
import numpy as np
import flopy.modflow as fpm
import flopy.modpath as fmp
import flopy.utils as fpu
import flopy.export.utils as fpexp
import flopy.utils.binaryfile as bf
import flopy.plot.map as fpp
import flopy.plot.crosssection as fcc
import matplotlib.pyplot as plout
import sys, getopt

print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('                  MODPATH SIMULATION                            ')
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
#indice = np.take(sys.argv[1:], 0)
print("Performing simulation for Melipilla model")
modeldir    = "2_Modelo/"
nameflow    = "gw"
namepath    = "path"

print('_____________________')
print('      Using ModPath 6')
print('_____________________')
if not os.path.exists(modeldir):
    os.mkdir(modeldir)

print('_____________________')
print('Retrieving input files')
print('_____________________')
shutil.copy2("2_Modelo/Melipilla.bas",  modeldir+nameflow+'.bas')
shutil.copy2("2_Modelo/Melipilla.dis",  modeldir+nameflow+'.dis')
shutil.copy2("2_Modelo/Melipilla.drn",  modeldir+nameflow+'.drn')
shutil.copy2("2_Modelo/Melipilla.lpf",  modeldir+nameflow+'.lpf')
shutil.copy2("2_Modelo/Melipilla.oc",   modeldir+nameflow+'.oc')
shutil.copy2("2_Modelo/Melipilla.pcgn", modeldir+nameflow+'.pcgn')
shutil.copy2("2_Modelo/Melipilla.rch",  modeldir+nameflow+'.rch')
#shutil.copy2("2_Modelo/Melipilla.wel",  modeldir+nameflow+'.wel')

print('_____________________')
print('Retrieving output files')
print('_____________________')
shutil.copy2("2_Modelo/Melipilla.cbc", modeldir+nameflow+'.cbc')
#shutil.copy2("2_Modelo/Melipilla.ddn", modeldir+nameflow+'.ddn')
shutil.copy2("2_Modelo/Melipilla.hds", modeldir+nameflow+'.hds')

print('_____________________')
print('Creating Melipilla model')
print('_____________________')
f1 = open(modeldir+nameflow+'.nam', 'w')
f1.writelines('# Name file for MODFLOW-2005, generated by Flopy version 3.2.11.\n')
f1.writelines('#xll:0; yll:0; rotation:0; proj4_str:EPSG:4326; units:meters; lenuni:2; length_multiplier:1 ;start_datetime:1-1-1970\n')
f1.write('{:14s} {:5d}  {}\n'.format('LIST', 2, nameflow+'.list'))
f1.write('{:14s} {:5d}  {}\n'.format('DIS', 11, nameflow+'.dis '))
f1.write('{:14s} {:5d}  {}\n'.format('BAS6', 13, nameflow+'.bas '))
f1.write('{:14s} {:5d}  {}\n'.format('LPF', 15, nameflow+'.lpf '))
f1.write('{:14s} {:5d}  {}\n'.format('RCH', 19, nameflow+'.rch '))
f1.write('{:14s} {:5d}  {}\n'.format('DRN', 21, nameflow+'.drn '))
f1.write('{:14s} {:5d}  {}\n'.format('WEL', 20, nameflow+'.wel '))
f1.write('{:14s} {:5d}  {}\n'.format('PCGN', 27, nameflow+'.pcgn '))
f1.write('{:14s} {:5d}  {}\n'.format('OC', 14, nameflow+'.oc '))
f = nameflow+'.hds'
f1.write('DATA(BINARY)   {0:5d}  '.format(51) + f + ' REPLACE\n')
f = nameflow+'.ddn'
f1.write('DATA(BINARY)   {0:5d}  '.format(52) + f + ' REPLACE\n')
f = nameflow+'.cbc'
f1.write('DATA(BINARY)   {0:5d}  '.format(1053) + f + ' REPLACE\n')
f1.close()

print('_____________________')
print('Retrieving properties')
print('_____________________')
m           = fpm.Modflow()
mymodelflow = m.load(nameflow+'.nam', version='mf2005', exe_name='mf2005.exe', verbose=False, model_ws=modeldir, load_only=None, forgive=True, check=True)
mybas       = mymodelflow.get_package('BAS6')
mydis       = mymodelflow.get_package('DIS')
mypcgn      = mymodelflow.get_package('PCGN')
mywel       = mymodelflow.get_package('WEL')
myzon       = mymodelflow.get_package('ZONE')
ncol        = np.unique(mydis.ncol)[0]
nrow        = np.unique(mydis.nrow)[0]
nlay        = np.unique(mydis.nlay)[0]

mymodelpath = fmp.Modpath(modelname = namepath, simfile_ext = 'mpsim', namefile_ext = 'mpnam', version = 'modpath', exe_name = 'mp6.exe', \
                          modflowmodel = mymodelflow, dis_file = nameflow+'.dis', dis_unit = 87, head_file = nameflow+'.hds', budget_file = nameflow+'.cbc', \
						  model_ws = modeldir, external_path = None, verbose = True, load = True, listunit = 7)

print('_____________________')
print('Porosity & boundaries')
print('_____________________')
Phi1       = 0.10
Phi2       = 0.10
Phi3       = 0.10

Phi        = np.empty([nlay, nrow, ncol])
for num in range(0,nlay):
    if   num <= nlay*1/3+1:
        Phi[num, :] = Phi1;
    elif num <= nlay*2/3+1:
        Phi[num, :] = Phi2;	
    else:
        Phi[num, :] = Phi3;	
	
bound      = np.ones([nlay, nrow, ncol], dtype=np.int32)
laytype    = np.zeros(nlay)
laytype[0] = 1
						  
mypathbas   = fmp.ModpathBas(model = mymodelpath, hnoflo = -9999.0, hdry = -8888.0, laytyp = laytype, ibound = bound, prsity = Phi, extension = 'mpbas',\
              unitnumber=86)
			  
mypathbas.write_file()
mymodelpath.write_input()		

print('_____________________')
print('    Transport options')
print('_____________________')
print('                     ')
SimulationType 	        	= 2 #2: pathline
TrackingDirection        	= 2 #2: Backward
WeakSinkOption 		        = 1 ##1: pass through
WeakSourceOption 	        = 2 ##1: pass through
ReferenceTimeOption         = 1 #absolute time
StopOption 			        = 2 #2 until they reach termination pos 
ParticleGenerationOption    = 2 #loc from sloc file
TimePointOption 	        = 1 #no activation of TimePointOption
BudgetOutputOption 	        = 1 #no record
ZoneArrayOption 	        = 1 #zone array data not read
RetardationOption 	        = 1 #retardation data not read
AdvectiveObservationsOption = 1 #no observation file
options = [SimulationType, TrackingDirection, WeakSinkOption, WeakSourceOption, ReferenceTimeOption, StopOption, ParticleGenerationOption, \
           TimePointOption, BudgetOutputOption, ZoneArrayOption, RetardationOption, AdvectiveObservationsOption]

loc_file                    = namepath+'.loc'
shutil.copy2("path"+".loc", modeldir+loc_file)
ReferenceTime               = 2000

mypathsim = fmp.ModpathSim(model = mymodelpath, mp_name_file = namepath+'.nam', mp_list_file = namepath+'.list', extension = 'mpsim', \
                           option_flags = options, ref_time = ReferenceTime) 
mypathsim.write_file()

print('Options flags:')
print('SimulationType ', 				mypathsim.options_dict['SimulationType'])
print('TrackingDirection ', 			mypathsim.options_dict['TrackingDirection'])
print('WeakSinkOption ', 				mypathsim.options_dict['WeakSinkOption'])
print('WeakSourceOption ', 				mypathsim.options_dict['WeakSourceOption'])
print('ReferenceTimeOption ', 			mypathsim.options_dict['ReferenceTimeOption'])
print('StopOption ', 					mypathsim.options_dict['StopOption'])
print('ParticleGenerationOption ', 		mypathsim.options_dict['ParticleGenerationOption'])
print('TimePointOption ', 				mypathsim.options_dict['TimePointOption'])
print('BudgetOutputOption ', 			mypathsim.options_dict['BudgetOutputOption'])
print('ZoneArrayOption ', 				mypathsim.options_dict['ZoneArrayOption'])
print('RetardationOption ', 			mypathsim.options_dict['RetardationOption'])
print('AdvectiveObservationsOption ', 	mypathsim.options_dict['AdvectiveObservationsOption'])
print('Particle location indicated in file: ', modeldir+loc_file)
print('              ')

print('_____________________')
print('                  RUN')
print('_____________________')

success, buff = mymodelpath.run_model(silent=False, pause=False, report=True, normal_msg='normal termination')
if not success:
    print(buff)
    raise Exception('MODFLOW did not terminate normally.')

shutil.copy2("modelpath.py", modeldir+"modelpath.py")


#print ('Creating zone array')
# zonearray = np.zeros([nr, nc], dtype=np.int32)
# zonearray[49, 120] = 1
# f1 = open(modeldir+"layerwell.txt", 'w+')
# #f1.writelines('10 \n')
# for k in range(14,24):
    # #curzone = 'Well'+str(k)
    # #f1.writelines(curzone)
    # #f1.writelines("\n")
    # #f1.writelines("INTERNAL 1 \"(FREE)\"  1\n")
    # for i in range(0,nr):
        # f1.writelines("%s " % item  for item in zonearray[i, :])
        # f1.writelines("\n")
#################################################
########option_flags #up to 12 options
#1: 	SimulationType 													#1: endpoint, 							2: pathline, 	3: timeseries, 	4: path-tser
#2: 	TrackingDirection 												#1: Forward, 							2: Backward
#3: 	WeakSinkOption 													#1: pass through, 						2: stop at
#4: 	WeakSourceOption												#1: pass through, 						2: stop at
#5: 	ReferenceTimeOption												#1: absolute time, 						2: stress period + time step+ time position within the step
#6: 	StopOption														#1: @end (for.) or beginning (back.) of the simulation time 
																		#2: until they reach termination pos 
																		#3: specific value to be specified
#7: 	ParticleGenerationOption							 			#1: loc from simulation file, 			2: from file
#8: 	TimePointOption	(for SimulationType = 3 or 4 ???)				#1: no activation of TimePointOption, 	2: #nb of times in a time interval, 3: list of time points
#9: 	BudgetOutputOption												#1: no record	
																		#2: cell water balance record 
																		#3: cell water balance record + budget record header
																		#4: detailed particle tracking info
#10: 	ZoneArrayOption													#1: zone array data not read, 			2: read
#11:	RetardationOption												#1: retardation data not read, 			2: read
#12: 	AdvectiveObservationsOption										#1: no observation file, 				2: observation file

#################################################
###### suboption NOT IN OPTION FLAGS

# Depending on 		*SimulationType*
	# endpoint_file		(SimulationType = 1)							#name of the MODPATH endpoint file
	# pathline_file 	(SimulationType = 2 or 4)						#name of the MODPATH pathline file
	# time_ser_file 	(SimulationType = 3 or 4)						#name of the MODPATH timeseries file
#Depending on 		*ReferenceTimeOption*				
	# ref_time 			(ReferenceTimeOption = 1)						#simulation time that marks the beginning of a MODPATH simulation
	# ref_time_per_stp 	(ReferenceTimeOption = 2) 						#period, time step & time fraction ([0,1])	
# Depending on 		*StopOption*													
	# stop_time 		(StopOption = 3)								#specific time value to stop simulation		
# Depending on 		*ParticleGenerationOption*	
	# group_ct 			(ParticleGenerationOption=1)					#nb of particle groups (int)
	# group_name 		(ParticleGenerationOption=1)					#particles group name (16 characters max)
	# part_ct 															#nb of particle in each groups ex: [[1, 1, 1]]	
	# group_placement 	(ParticleGenerationOption=1)					#Grid, GridCellRegionOption, PlacementOption, ReleaseStartTime, ReleaseOption, CHeadOption  ex: [[1, 1, 1, 0, 1, 1]]
			# group_region 	(GridCellRegionOption = 1)					#MinLayer, MinRow, MinColumn, MaxLayer, MaxRow, MaxColumn ex: [[1, 1, 1, 1, 1, 1]]
			# mask_nlay 	(GridCellRegionOption = 2)					#ex: [1]
			# mask_layer	(GridCellRegionOption = 3)					#ex: [1]
			# mask_1lay 	(GridCellRegionOption = 3)					#ex: [1]			
			# face_ct 		(PlacementOption = 1)						#ex: [1]
			# ifaces 		(PlacementOption = 1)						#IFace, ParticleRowCount, ParticleColumnCount ex: [[6, 1, 1]]
			# particle_cell_cnt  (PlacementOption = 2)					#ParticleLayerCount, ParticleRowCount, ParticleColumnCount ex: [[2, 2, 2]]				
			# ReleaseStartTime	(qqsoit ReleaseOption)					#1st release time (ReleaseOption = 2) and unique (ReleaseOption = 1)					
			# release_times (ReleaseOption = 2)							#multiple points in time based on period length: ReleasePeriodLength, ReleaseEventCount ex: [[1, 1]] 
			# release_times (ReleaseOption = 3)							#multiple points in time based on release times: ReleaseTime, ReleaseEventCount ex: [[1, 1]]  ??????	
	# strt_file			(ParticleGenerationOption=2)					#name of the starting locations file
# Depending on 		*TimePointOption*
	# time_ct 			(TimePointOption = 2 or 3)						#number of time points, #nb of time point data to be specified for MODPATH simulations
	# release_time_incr	(TimePointOption = 2)							#uniform interval of time between time points
	# time_pts 			(TimePointOption = 3)							#array of time points [size of time_ct]
# Depending on 		*BudgetOutputOption
    # cell_bd_ct		(BudgetOutputOption = 3)						#number of cells for which detailed water budgets are computed
	# bud_loc			(BudgetOutputOption = 3)						#array of cell numbers (Grid, Layer+1, Row+1, Column+1) ex:[[1, 1, 1, 1]]
	# trace_file		(BudgetOutputOption = 4)						#name of the MODPATH trace file
	# trace_id 			(BudgetOutputOption = 4)						#which grp is followed
# Depending on 		*ZoneArrayOption	
	# stop_zone 		(ZoneDataOption = 2)							#specified integer zone value for automatic stopping location for particles (0 = no stop)
	# zone				(ZoneDataOption = 2)							#array of positive integer zones
# Depending on 		*RetardationOption	
	# retard_fac		(RetardationOption = 2)							#array of retardation factors
	# retard_fcCB		(RetardationOption = 2)							# ?????
# Depending on 		*AdvectiveObservationsOption
	# advobs_file		(AOO = 2 & SimulationType = 3 - timeseries)		# create an observation file for time series?????